constituencies = [
    'Ainabkoi',
    'Aldai',
    'Algunyi-Manu',
    'Amagoro',
    'Amu-Kipevu',
    'Asego',
    'Asumbi',
    'Athi River',
    'Awendo',
    'Bahari',
    'Bahati',
    'Balambala',
    'Bamba',
    'Banissa',
    'Baragoi',
    'Baringo Central',
    'Baringo North',
    'Baringo South',
    'Barut',
    'Batei',
    'Belgut',
    'Bensa',
    'Bokoli',
    'Bomet Central',
    'Bomet East',
    'Bomet West',
    'Bonchari',
    'Bongomek',
    'Bonyunyu',
    'Borabu',
    'Budalangi',
    'Buhuyi',
    'Bumula',
    'Bunyala',
    'Burder',
    'Burguret',
    'Busia',
    'Butere',
    'Butula',
    'Buyofu',
    'Cabarnet',
    'Carbacid',
    'Catherine Wambilianga',
    'Central Imenti',
    'Central Kanyamkago',
    'Central Kasipul',
    'Central Kisumu',
    'Central Sotik',
    'Central West Gem',
    'Chaani',
    'Changamwe',
    'Chepalungu',
    'Cherab',
    'Chesumei',
    'Chewoyet',
    'Chilchila',
    'Chuka/Igambangombe',
    'Dagoretti North',
    'Dagoretti South',
    'Dadaab',
    'Dandora I',
    'Dandora II',
    'Dandora III',
    'Daraja',
    'Daughty',
    'Dedamar',
    'Dedza',
    'Devali',
    'Dhondobola',
    'Diangani',
    'Dida',
    'Dieyo',
    'Dimu',
    'Dondori',
    'Donholm',
    'Dororo',
    'Dukana',
    'East Mbita',
    'East Seme',
    'Eldas',
    'Eldoret Central',
    'Eldoret East',
    'Eldoret North',
    'Eldoret South',
    'Embakasi Central',
    'Embakasi East',
    'Embakasi North',
    'Embakasi South',
    'Embakasi West',
    'Emuhaya',
    'Endebess',
    'Endebess',
    'Engwen',
    'Eregi',
    'Esantos',
    'Esiwani',
    'Etangeta',
    'Fafi',
    'Faza',
    'Gachoka',
    'Galbet',
    'Galma',
    'Galole',
    'Gambogi',
    'Ganze',
    'Garsen',
    'Gatanga',
    'Gatanga',
    'Gathuthi',
    'Gatundu North',
    'Gatundu South',
    'Gede',
    'Gichugu',
    'Gigiri',
    'Gilgil',
    'Gitaru',
    'Gitugi',
    'Godoma',
    'Gwassi',
    'Habaswein',
    'Haji Mohamed',
    'Hamisi',
    'Hawag',
    'Homa Bay Town',
    'Huruma',
    'Huruma',
    'Ichagaki',
    'Ichamara',
    'Ichuni',
    'Ida Odinga',
    'Igembe Central',
    'Igembe North',
    'Igembe South',
    'Igoji',
    'Igwamiti',
    'Ijara',
    'Ikolomani',
    'Ilchamus',
    'Imeni',
    'Ingotse/Matiang\'i',
    'Isebania',
    'Isiolo Central',
    'Isiolo North',
    'Isiolo South',
    'Isiolo South',
    'Iten',
    'Ivagaci',
    'Ivette',
    'Ivumwe',
    'Jomvu',
    'Jonglei',
    'Juja',
    'Kabete',
    'Kabondo Kasipul',
    'Kaboni',
    'Kabula',
    'Kacheliba',
    'Kadaari',
    'Kadika',
    'Kadzandani',
    'Kadzengo'
    
    
]
  